### ISSUE TITLE
CPU usage keeps 99%~100%

### ISSUE THREAD

**Issue by YuhangGe** [uranusjr/macdown#174]
same with #53 

try this file: https://github.com/YuhangGe/guitar/blob/master/iosapp/README.md , even disabled auto-render option and type nothing, the CPU usage is 99%~100%.

osx 10.10, mac book air.

**Comment by coolynx** [comment]
Here is another way of getting 100% CPU usage with simple code.
Paste this code into a new file https://gist.github.com/coolynx/14f7a085842bd62c8d1c

**Comment by niftylettuce** [comment]
Same issue, 186% cpu! :bar_chart:

**Comment by drekka** [comment]
Having the same problem here. Also getting issues with the rendering in the edit pane. I'm seeing words with incorrect fonts, or changing from normal to bold and changing colour in mid word.

**Comment by mfeblowitz** [comment]
My MBP's CPU utilization goes to near 100% for both MacDown and MOU. I'm wondering whether there's some code in common that exhibits the same behavior. Also, I've only seen this recently for MOU (that's why I jumped to MacDown). I'm not sure whether it's OS X version related (10.11.3) or perhaps due to something in my .md files (e.g., nbsp, image, ...)?

**Comment by niftylettuce** [comment]
see https://github.com/niftylettuce/seuss.md and follow me on twitter, I'm
building a MacDown alternative over weekends, it's nearly done

On Wed, Feb 24, 2016 at 1:02 PM, Mark Feblowitz <notifications@github.com>
wrote:

> My MBP's CPU utilization goes to near 100% for both MacDown and MOU. I'm
> wondering whether there's some code in common that exhibits the same
> behavior. Also, I've only seen this recently for MOU (that's why I jumped
> to MacDown). I'm not sure whether it's OS X version related (10.11.3) or
> perhaps due to something in my .md files (e.g., nbsp, image, ...)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uranusjr/macdown/issues/174#issuecomment-188384311>.
>



-- 
@niftylettuce

**Comment by uranusjr** [comment]
The upstream has issued a fix that is merged to MacDown 0.6. I will close this for now, but please feel free if CPU spikes still happen. We are not sure whether this has been completely fixed.

Please supply a sample document that can re-produce the behaviour if you re-open this.
