### ISSUE TITLE
Compile error for handlebars-objc.ym

### ISSUE THREAD

**Issue by tkawachi** [uranusjr/macdown#220]
I tried to compile, but a following error occurred.

````
Yacc handlebars-objc/src/handlebars-objc/parser/handlebars-objc.ym
    cd /Users/kawachi/.ghq/github.com/uranusjr/macdown/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/yacc -fno-objc-arc -d -b /Users/kawachi/Library/Developer/Xcode/DerivedData/MacDown-dtaxgfutnpvuvsbwranejrvmylru/Build/Intermediates/Pods.build/Debug/Pods-MacDown-handlebars-objc.build/DerivedSources/y /Users/kawachi/.ghq/github.com/uranusjr/macdown/Pods/handlebars-objc/src/handlebars-objc/parser/handlebars-objc.ym

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- f
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/yacc failed with exit code 1
````

It seems to be related with https://github.com/CocoaPods/CocoaPods/issues/2559.

**Comment by JanX2** [comment]
This stopped me from being able to build for a while. If this persists, this should go into the docs.

**Comment by uranusjr** [comment]
It’s [already in the docs](https://github.com/uranusjr/macdown/blob/master/README.md#requirements). I honestly don’t know what is stopping them from issuing a quick-n-dirty fix. It’s almost like they don’t even care.

**Comment by JanX2** [comment]
This has resurfaced after installing with bundler.

	jan$ bundle install
	Using i18n 0.7.0
	Using multi_json 1.10.1
	Using activesupport 3.2.21
	Using claide 0.7.0
	Using fuzzy_match 2.0.4
	Using json_pure 1.8.2
	Using nap 0.8.0
	Using cocoapods-core 0.34.4
	Using cocoapods-downloader 0.7.2
	Using cocoapods-plugins 0.3.2
	Using netrc 0.7.8
	Using cocoapods-trunk 0.3.1
	Using cocoapods-try 0.4.3
	Using colored 1.2
	Using escape 0.0.4
	Using open4 1.3.4
	Using xcodeproj 0.19.4
	Using cocoapods 0.34.4
	Using bundler 1.9.2
	Bundle complete! 1 Gemfile dependency, 19 gems now installed.
	Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by uranusjr** [comment]
You’ll need to run `bundle exec pod install` again after `bundle install`. The readme has been updated, but I see the Travis script is not. I’ll fix this.

**Comment by JanX2** [comment]
Thanks!
