### ISSUE TITLE
Automatically create the markdown file

### ISSUE THREAD

**Issue by jlhg** [uranusjr/macdown#233]
When writing the docs, it is convenient if I create a link, e.g. `[chapter_1](chapter_1.md)`, and click the link in the preview pane, MacDown will automatically create a new file "chapter_1.md" at the same location (or subdirectory) if that file is not found.

**Comment by uranusjr** [comment]
I ended up implementing a slightly different solution. If you click on a (local, obviously) file that doesn’t exist, MacDown will open a new document, and set its URL for you. The document is not created on disk—you will need to save it yourself later—but when you do, MacDown automatically navigates to the correct directory, and sets the correct filename for you.

This will be a opt-in feature in the next release.
