### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Xiaosen0624** [uranusjr/macdown#238]
I tried to compile, but got 3 errors, using cocoa pods 0.34.4,

1. this target :peg-markdown-highlight, got 

>error:/Users/xiaosen/Code/Github/Utils/Macdown2/Dependency/peg-markdown-highlight/greg.c:3:10: 'stdio.h' file not found

2. this target:MacDown  got 2 errors:

>Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

and 

>(null): Linker command failed with exit code 1 (use -v to see invocation)

more details:

> clang: error: no such file or directory: '/Users/xiaosen/Code/Github/Utils/Macdown2/Dependency/peg-markdown-highlight/pmh_parser.c'

and

> ld: file not found: /Users/xiaosen/Library/Developer/Xcode/DerivedData/MacDown-adblikfyalmizpcrdwhuefkjnjle/Build/Intermediates/MacDown.build/Debug/MacDown.build/Objects-normal/x86_64/pmh_parser.o

**Comment by uranusjr** [comment]
I’m not entirely sure, but maybe you need to install **command line tools** in Xcode first? `greg.c` is built with an external Makefile, and maybe that’s what causes the problem.

**Comment by insidegui** [comment]
Yeap! `xcode-select --install` fixed It :) Happy new year!

**Comment by uranusjr** [comment]
Great! I’ll add this to the README to prevent others hitting this problem. :)

**Comment by Xiaosen0624** [comment]
thanks a lot, it works now

**Comment by mykoma** [comment]
And I also need run the command ```make``` under "peg-markdown-highlight" folder,

**Comment by uranusjr** [comment]
@mykoma That’s strange… The Xcode project is supposed to handle that for you. Can you provide a way to reproduce this with a fresh git clone? Open a new issue with the steps and I will investigate.

**Comment by besi** [comment]
@uranusjr I just did a clean clone on macOS Catalina 10.15.1 (19B88) and I did run into the same problem and had to run make inside of `macdown/Dependency/peg-markdown-highlight` first in order to compile the app.
