### ISSUE TITLE
Added basic support for the Julia language in prism

### ISSUE THREAD

**Issue by cdagnino** [uranusjr/macdown#243]
Hi, I added basic support in prism for the Julia language [here](https://github.com/LeaVerou/prism/pull/467). The PR has been merged and the language ID is `julia` in Prism if you want to add it to the list of supported language IDs (or I can do that myself as a PR if you tell me how to do it!)

**Comment by uranusjr** [comment]
I usually update Prism right before a new release, so this is definitely coming with the next one! Do you this we should add some language aliases for it? We have `py` for `python`, for example. If there’re common aliases for Julia, I can add them too.

**Comment by cdagnino** [comment]
Thanks for the quick reply. I would add `jl` too. Does that need to go into
prism or are aliases handled internally by macdown?

**Comment by uranusjr** [comment]
No, aliases are maintained by MacDown (since Prism does not implement this yet). I’ll add it later. :)
