### ISSUE TITLE
Don't count words in fenced code blocks

### ISSUE THREAD

**Issue by ajdavis** [uranusjr/macdown#244]
Hi, I love MacDown. I'm writing a book chapter in Markdown and I want to write a certain number of words, so I'm heavily relying on MacDown's "Show word count" feature. My chapter also contains a lot of code, and I don't want to count word-like text strings in the code blocks, I only want to count regular words outside of code.

**Comment by uranusjr** [comment]
This is reasonable, but how about inline code? Should they be excluded too?

Maybe we should count each code block/span as *one* word? so `this would be a word`, and

```markdown
* This would be one word, too.
```

I’m not very familiar with this, to be honest—is there some consensus over this in the tech-writing community?

**Comment by ajdavis** [comment]
I think inline code should be one word, and fenced code should be no words. I don't know if there's a consensus in the tech-writing community, but my editor for Architecture of Open Source Applications told me to aim for 8000 words "excluding code examples".

**Comment by uranusjr** [comment]
Makes sense to me. I’ll fix the behaviour, and we can always change it or add more counting options if there are different needs.

**Comment by ajdavis** [comment]
Thanks!

**Comment by ajdavis** [comment]
Thanks for the fix, works pefectly in 0.4.2.
