### ISSUE TITLE
Clicking on a footnote opens XCode

### ISSUE THREAD

**Issue by ajdavis** [uranusjr/macdown#245]
MacDown Version 0.4.1 (535), Mac OS X 10.9.5, XCode 6.1.1. The first click on each footnote in the MacDown editor, or the first click on a link from a footnote back to the source reference mark, first opens XCode with the Markdown file. The second click jumps within the MacDown editor as expected.

Here's a demo of the bug:

https://www.youtube.com/watch?v=PNqlLIzjRKg

**Comment by uranusjr** [comment]
Strangely, clicking on footnotes doesn’t work *at all* on my machine (running Yosemite). Honestly I never tried clicking on footnotes, so I’ll have to find a Mavericks machine to find out why this behavioural difference exists, and then look into this problem.

Thanks for reporting!

**Comment by ajdavis** [comment]
I see that XCode is the default application for opening Markdown files on my Mac:

![screen shot 2015-01-17 at 9 32 13 pm](https://cloud.githubusercontent.com/assets/84101/5791200/83fca060-9e90-11e4-8fe8-8e8dde008503.png)

So I changed the default application for Markdown to MacDown:

![screen shot 2015-01-17 at 9 32 27 pm](https://cloud.githubusercontent.com/assets/84101/5791202/991019f0-9e90-11e4-93fc-de4dbf7116f9.png)

Now every **second** mouseclick on a footnote, or on the footnote's reference mark, does what I expect: the editor jumps within the Markdown file between the footnote and its reference mark. I still don't know why it requires two clicks instead of one click.

**Comment by uranusjr** [comment]
So the main problem is that most of the time, links are now opened in a new document in the workspace (e.g. browser for HTTP links, Finder for `file://`), and HTML anchors count as links too. When you click on the footnote anchor (e.g. `#fn1`), the workspace will try to open `file://<path to current file>#fn1`, which opens whatever default editor the user sets for Markdown documents.

I find the “works the second time” behaviour pretty interesting, personally. Apparently, when OS X opens a URL (file or HTTP or whatever) in a window, it kind of remembers that, and try to reuse the same window for subsequent URL clicks. This is probably why Safari (sometimes) opens only new window if you click on a link several times, and why Finder reuses existing windows when you click the “reveal in Finder” thing in the menu. Anyway, assuming MacDown is the default app for Markdown documents, OS X reuses the same document window when you click on a URL that corresponds to that same document again, making the anchor jump actually work.

And the next question would probably be why it isn’t smart enough to know this the first time. I don’t know; maybe there’re other reasons behind it. But at least inside our app we can handle the links internally without round-tripping to the OS, which should eliminate the problem completely.

Barring unexpected problems, I think I will release a minor update this weekend.

**Comment by ajdavis** [comment]
Neat, thank you!

**Comment by ajdavis** [comment]
Thanks for the fix in 0.4.2!
