### ISSUE TITLE
Windows keep going background after drag and drop images to editor

### ISSUE THREAD

**Issue by diimdeep** [uranusjr/macdown#250]

**Comment by uranusjr** [comment]
I seem to unable to reproduce this on my machine. Could you be more specific on what happened (maybe record a short video or something)? Also it would be nice if you could provide some information about your computer (MBP/MBA/iMac, Retina or not, Yosemite/Mavericks/Snow Lion, etc.).

**Comment by diimdeep** [comment]
Can't reproduce either, maybe some bug in cocoa or interference from other
software.

**Comment by uranusjr** [comment]
I guess I’ll close this for now then. Feel free to reopen this if it happens (with consistency) again.
