### ISSUE TITLE
Block quotes in editor

### ISSUE THREAD

**Issue by ohthetrees** [uranusjr/macdown#252]
Hi, thanks for the great program. I have a usability quibble. 

Typing the following sequence yields different behavior in Markdown and Mou, and I think Mou's is better. 

`> This is a quote \n\n This is not a quote\n\n\n\n`

In Macdown, the following appears in the editor:
```
> This is a quote
> 
> This is not a quote
> 
> 
> 
```

Where in Mou, we see this (preferable to me):
```
> This is a quote

This is not a quote


```

Hope that's clear!

The only way I've found to get Macdown to stop auto-adding the `>` at the beginning of each line is to hit delete a few times.

Thanks again for this great product.

**Comment by aaronraimist** [comment]
Maybe this should be included in the "Auto-complete matching characters" option in the editor preferences.

**Comment by uranusjr** [comment]
If you want to “break” out of a blockquote block, you can use **command-return** (instead of just return), which closes the current block and start a new one.

But yes, this (and the list item completion, which works similarly) should be configurable.

**Comment by ohthetrees** [comment]
The command-return trick is totally adequate for me. Thanks!
