### ISSUE TITLE
Feature Request: Auto add square brackets to selected text when press "[" key

### ISSUE THREAD

**Issue by puttin** [uranusjr/macdown#254]
Just like Mou.

**Comment by uranusjr** [comment]
This should already work if you tick the “Auto-complete matching characters” option.

**Comment by puttin** [comment]
That's great!

But I noticed that it confused me when editing in code block.

**Comment by uranusjr** [comment]
Yeah, currently there’s no way to tell whether you’re in a code block or not, so it’s kind of all-or-nothing. That cannot be helped—sorry.

**Comment by puttin** [comment]
Never mind. It's just a plus.
