### ISSUE TITLE
Only first footnote will render correctly v0.4.2(578)

### ISSUE THREAD

**Issue by puttin** [uranusjr/macdown#258]
Checkout `MacDown Helper` in `Help` menu

**Comment by uranusjr** [comment]
You’re right! I messed with `help.md` sometime ago and obviously the changes are sloppy. Thanks for reporting, fixed!

**Comment by puttin** [comment]
But I noticed that
```
a [^1]

n [^1]

[^1]: a
```

will render to:

![screen shot 2015-02-02 at 18 39 28](https://cloud.githubusercontent.com/assets/1543629/5999235/dac40bf0-ab0a-11e4-864a-34203cafbb6c.png)

**Comment by uranusjr** [comment]
Yes, this is a Markdown thing. Footnotes need to be distinct. See discussion at hoedown/hoedown#92.

**Comment by puttin** [comment]
So I guess 
```
[example][example]

[the example][example]

[example]: http://example.com
```

would be the solution now

**Comment by uranusjr** [comment]
Or you could use plain HTML:

    a [^1]

    n <sup><a href="#fn1">1</a></sup>

    [^1]: a

**Comment by puttin** [comment]
Thanks!
