### ISSUE TITLE
Math render between \begin{equation} and  \end{equation}

### ISSUE THREAD

**Issue by wantee** [uranusjr/macdown#265]
I need to use the [Automatic Equation Numbering](http://docs.mathjax.org/en/latest/tex.html#automatic-equation-numbering)  feature of MathJax, so I have to use the *equation* environment. But Macdown behaves strangely. Here is the example:

when I type the following codes, it can't render rightly

```
\begin{equation}
S_i = y_i
\end{equation}
```
But
```
\begin{equation}
S_i = y
\end{equation}
```
or
```
\begin{equation}
S = y_i
\end{equation}
```
is OK.

How can I fix it? and would Macdown support automatic equation numbering?

PS: Version of Macdown is 0.4.2 (578) with OSX Mavericks 10.9.5

**Comment by uranusjr** [comment]
`\begin{equation}` and `\end{equation}` are not included in MacDown as math environment triggers to prevent collision with Markdown’s syntax.

If you *have* to use `\begin{equation}` and `\end{equation}` (or any environments other than the [supported syntaxes](http://macdown.uranusjr.com/features/)), you will need to escape underscores manually:

    \begin{equation}
    S\_i = y\_i
    \end{equation}

Closing as wontfix.
