### ISSUE TITLE
Boundary between editor and preview needs to exist

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/macdown#266]
Starting from 0.4.2, the separator between editor and preview panes are now decorated so that it is invisible. This however can be problematic if the editor and preview panes have the same background colour. Example:

![10937554_10200261066844881_1718735859_n](https://cloud.githubusercontent.com/assets/605277/6063701/32766312-ad94-11e4-821c-08c1d6612729.jpg)

I think the solution to this should be to **draw the separator with another colour when both panes are visible, and the background colours are similar**. Obviously need to define “similar” here, and also need to decide what colour the separator should be in these cases.

**Comment by Jmuccigr** [comment]
I would just make it a preference to have a dividing line. Make the color part of the theme.
