### ISSUE TITLE
Re-number footnotes automatically

### ISSUE THREAD

**Issue by Jmuccigr** [uranusjr/macdown#268]
When editing docs, I often move around text that contains footnote. It would be great if those would either automatically renumber, or if there were a clean-up routine that would re-number footnotes in order from top to bottom.

This would also make it less important to remember what number the footnotes were up to  when working on a long doc, or when inserting some next text.

**Comment by ohthetrees** [comment]
Since footnotes don't have to be given numerical names, this could get tricky.

`[^dingleberry47b]` is a perfectly good footnote id.

**Comment by Jmuccigr** [comment]
Ah, did not realize that. I was hoping that the footnote text wouldn't matter at all, like the numbers in numbered lists, and then the footnote text would be the first one following the reference.

**Comment by ohthetrees** [comment]
Afraid not. In fact, I tend to collect my footnotes at the bottom of the document, just like real footnotes. They can go in any order, and have any ids, and they will be rendered in the order they were referenced, and be given sequential numbers. I actually give my ids names that help me remember what they are, like this `[^footnote naming]`[^footnote naming]

[^footnote naming]: The footnote id is arbitrary. And it looks like footnotes aren't supported in comments.

**Comment by uranusjr** [comment]
GitHub does not support footnote. Which IMO is part of the reason why it works differently in different implementations—there’s not a de facto standard yet.

Anyway, @ohthetrees is correct. Footnote re-ordering would be either impossible or very error-prone to implement. I might be worthwhile to build some tools to help presenting an overview of footnotes though.
