### ISSUE TITLE
Scrolling with two fingers in input field is not smooth

### ISSUE THREAD

**Issue by Lhfcws** [uranusjr/macdown#271]
My Macbook: 10.10.2 on RMBP

I scrolled with two fingers in input field and found it not smooth at all. I have to scroll several times to just make it move up or down a little. Scrolling in view field and dragging the scrollbar are all fine.
Thank you.

**Comment by uranusjr** [comment]
Probably similar to #203? Try setting the system scroll behaviour, as mentioned in the comments.

**Comment by Lhfcws** [comment]
I've tried that and it seems not working....

**Comment by Lhfcws** [comment]
Great ! Latest build works fine! Thank you.
