### ISSUE TITLE
Mid-line comments not removed by parser.

### ISSUE THREAD

**Issue by jbkr** [uranusjr/macdown#276]
Opened a question on [SO](http://stackoverflow.com/questions/28417406/how-to-insert-a-mid-line-comment-in-markdown/28417560#28417560) and it appeared to be that the parser in MacDown cannot handle mid-line comments.

In markdown comments are made by `<!-- Comment -->`. However when I try to render the following text the comments remain in the render.

    Summary
    ---
    
    Some proteins  are ‘anchored’ into the membranes.

*i.e* It appears as:

 ![comment remains in render][1]

Whereas I am trying to get:

![comment removed][2].

I have tried a different [markdown parser](https://github.com/gruehle/MarkdownPreview) and the mid-line comments are removed.
  [1]: http://i.stack.imgur.com/z1BL2m.png
  [2]: http://i.stack.imgur.com/O9qYMm.png

**Comment by nkalvi** [comment]
It seems to be an open issue with underlying hoedown:
https://github.com/hoedown/hoedown/issues/115

Just to confirm, I processed your example with hoedown, and I can see that it is escaping the '<' and '>':
```
<h2>Summary</h2>

<!--intro-->

<p>Some proteins &lt;!-- the nanoscopic biological machines running our cells --&gt; are ‘anchored’ into the membranes.</p>

<h2>Summary</h2>

<!--intro-->

<p>&lt;!-- the nanoscopic biological machines running our cells --&gt; 
are ‘anchored’ into the membranes.</p>
```

**Comment by nkalvi** [comment]
Temporary workaround may be (sorry about non-elegant solution :):

```
Some proteins <span style="display:none"> the nanoscopic biological machines running our cells </span> are ‘anchored’ into the membranes.
```
or
```
<STYLE type="text/css">
   .inline-comment {display:none;}
</STYLE>

Summary
---
<!--intro-->

Some proteins <span class="inline-comment"> the nanoscopic biological machines running our cells </span> are ‘anchored’ into the membranes.
```
