### ISSUE TITLE
NSScrollView layout log message

### ISSUE THREAD

**Issue by JanX2** [uranusjr/macdown#281]
I am getting the following log entry when running the current HEAD (aa565a9ea635c63bd83cedf48b4f23449ccb05d9) of MacDown:

2015-02-13 15:27:31.261 MacDown[16235:63145] Layout still needs update after calling -[NSScrollView layout].  NSScrollView or one of its superclasses may have overridden -layout without calling super. Or, something may have dirtied layout in the middle of updating it.  Both are programming errors in Cocoa Autolayout.  The former is pretty likely to arise if some pre-Cocoa Autolayout class had a method called layout, but it should be fixed.

**Comment by uranusjr** [comment]
Yes, I have been seeing this for a while now, after I upgraded to 10.10. It is very easy to reproduce:

1. Create a new document-based application project in Xcode.
2. Implement read and write methods in the `NSDocument` subclass (don’t really need to do anything meaningful, just need to prevent the exceptions from being thrown but keep autosave working).
3. Somehow mark an untitled document dirty (the simplest way is to call `[self updateChangeCount:NSChangeDone]`).
4. Try to close the dirty untitled document. A save sheet will present itself to give you a chance to save the document (as is standard in OS X). And you will see the same log in your console.

So, I think this is actually an OS X bug, probably related to the problem in which [save sheets can grow automatically every time you open it](http://osxdaily.com/2014/12/08/resize-large-open-save-dialog-windows-mac-os-x/). I didn’t investigate further; it might still be fixable.

Closing this as wontfix. But I’ll be very happy to merge if you can somehow make this warning go away!

**Comment by JanX2** [comment]
Just for future reference, I neither saved nor created a new document and this was logged on launch even without any documents being restored.
