### ISSUE TITLE
Word wrap stops working

### ISSUE THREAD

**Issue by nindalf** [uranusjr/macdown#289]
When in editor only mode, you switch to the preview and back, the word wrap stops working correctly.

The line length changes to (as far as I can tell) 273 characters OR the length of two normal lines. This is apparent in the screenshot in the first line of the "Thread Safety" section. There doesn't seem to be any way of setting it right once it happens, other than to close and re-open the file.

Just after loading the file:

![screen shot 2015-02-17 at 11 05 25 am](https://cloud.githubusercontent.com/assets/1257998/6223695/5bef4c2c-b695-11e4-907f-133f41daecc6.png)

After switching to preview and back:

![screen shot 2015-02-17 at 11 05 55 am](https://cloud.githubusercontent.com/assets/1257998/6223696/5f1556f8-b695-11e4-8429-44db35db6f3c.png)

I'm running Yosemite on early 2013 13" retina macbook. If any further info is required, I'd be happy to provide that. If its a simple fix, please point me to the file that needs fixing and I'll try to do it (I have no prior experience with Obj-C)

**Comment by uranusjr** [comment]
What version of MacDown are you running? Also: does anything happen if you scroll in the editor? Can you scroll horizontally?

**Comment by nindalf** [comment]
I'm running Version 0.4.3 (606). Yes, I can scroll horizontally when this happens. Thanks for the prompt reply :smiley:

**Comment by kevincannon** [comment]
I'm seeing this issue sometimes too.

**Comment by nindalf** [comment]
I've seen a few updates since I reported this, one of which said that it fixed this issue. Kudos for the fast response, but I'm still seeing this happen.
