### ISSUE TITLE
Reload file if changed

### ISSUE THREAD

**Issue by ZevEisenberg** [uranusjr/macdown#296]
I like to do certain operations on a file in an external editor like TextMate. When I finish my changes in TextMate and I save the document, I would like MacDown to automatically reload the file when I switch back to it. TextMate and Xcode both do this, and it prevents against the case where two apps are trying to save conflicting changes to the same file.

**Comment by ohthetrees** [comment]
I think this is already being explored in #48 .

**Comment by uranusjr** [comment]
Yup, closing as duplicate. :)
