### ISSUE TITLE
Embed JavaScript?

### ISSUE THREAD

**Issue by epugh** [uranusjr/macdown#300]
I am writing a document, and want to link to a Google Trends chart that can be embedded via JavaScript...   Be nice to say "here is javascript, render it".   I know it's not a browser however....

**Comment by uranusjr** [comment]
Just put a `<script></script>` tag inside your document. It will be picked up automatically.

**Comment by epugh** [comment]
Oh sweet!    Thanks.

**Comment by epugh** [comment]
While I have your attention, I noticed that https://stackedit.io, a online markdown editor now allows you to do sequence diagrams in markdown.   It seems to be the same syntax as a tool I use all the time, http://websequencdiagrams.com.   I think they both use http://bramp.github.io/js-sequence-diagrams/

**Comment by uranusjr** [comment]
That is covered by #224 if I understand what you mean correctly. Anyway, closing this since the original problem is solved.
