### ISSUE TITLE
How SAS can be included in Syntax Highlighting

### ISSUE THREAD

**Issue by huyingjie** [uranusjr/macdown#302]
Golmote from Prism js wrote syntax highliting for SAS recently (https://github.com/PrismJS/prism/issues/515).

I want to use `sas` as language id in a similar way to other languages in page http://macdown.uranusjr.com/features/. 

How could it be achieved?

Thank you in advance!

**Comment by uranusjr** [comment]
TO put it in the core, I will need to pull the changes in Prism, and issue a new release. The first part is simple enough, but I’m not ready to release a new version just yet.

A workaround is to right-click on MacDown.app and select “Show Package Contents”. Navigate inside the new Finder window to `Contents/Resources/Prism`. This is a stripped-down version of the Prism repository; you will need to copy `components.js` and related component files (`components/prism-sas.min.js` and `components/prism-sas.js`) into it. After you’re done, restart MacDown, and use ```` ```sas ```` to enable highlighting.

**Comment by huyingjie** [comment]
Thank you. Now MacDown can show SAS correctly!
