### ISSUE TITLE
Nested lists are broken.

### ISSUE THREAD

**Issue by UnquietCode** [uranusjr/macdown#310]
This seems like an off-by-one error. When nesting lists, each new item requires one more space than the last in order to render properly in the preview. I believe the intent is that each new item requires a consistent two spaces to nest. (I actually think this is a recent breakage as I don't remember encountering it before.)

```md
* zero
  * two
     * five
         * nine
```

**Comment by uranusjr** [comment]
Duplicate to #148.

**Comment by UnquietCode** [comment]
Ok, thanks. So the recommendation is to use tabs or 4 spaces for indents.
