### ISSUE TITLE
Version 0.4.4 crashes immediately in OS X 10.8.5

### ISSUE THREAD

**Issue by jenmontes** [uranusjr/macdown#311]
The latest version of MacDown (0.4.4) fails to open in OS X Mountain Lion (10.8.5): double-clicking the app causes an immediate crash and display of the crash reporting dialog.

This behavior occurs both with the automatic update and by replacing the entire application.

The only way I can get MacDown to run is by keeping the 0.4.3 version.

**Comment by uranusjr** [comment]
Darn, you’re right. I used some APIs available only in 10.9+ when implementing the “preview pane position tracking” functionality. I will issue a new release shortly to make it at least usable.

Sorry about the inconvenience.
