### ISSUE TITLE
Default saving file name `Untitled.md`

### ISSUE THREAD

**Issue by eccstartup** [uranusjr/macdown#316]
I do think when the file saves, using the `first line` of the document as the name is better.

For example, the first non-empty line is `###Schedule for this week`. Using `Schedule-for-this-week` as the name of this name of file is better.

**Comment by eccstartup** [comment]
Maybe it is here.

https://github.com/uranusjr/macdown/blob/65dcba5b7d5fbfcd2045281e4941fd48136c8ae3/MacDown/Code/Document/MPDocument.m#L33

**Comment by uranusjr** [comment]
This should already work for both Markdown headings and Jekyll front-matters. But this will only work if the document is well-formed, so maybe not for your example—MacDown uses a slightly stricter syntax rule, and you need to write the title like this

    ### Schedule for this week

Notice that there is a space after `###`.

**Comment by eccstartup** [comment]
Cool!
