### ISSUE TITLE
Blank markdown document icon in Finder

### ISSUE THREAD

**Issue by ptzz** [uranusjr/macdown#320]
**Steps to reproduce**

1. Set Finder to column view
2. View -> Show View Options, change "Text size" to 12 or smaller

**Result**
The icon for .md files changes from the one in MarkdownDocument.icns to blank white

**Expected**
A smaller version of the MarkdownDocument.icns icon

**Setup**
Yosemite 10.10.2, non-retina mac

**Comment by uranusjr** [comment]
Confirmed. I’ll look into this.

**Comment by ptzz** [comment]
Just discovered that the issue is gone. Not sure how or when, maybe an update in OS X 10.10.3?

**Comment by uranusjr** [comment]
I can still see a blank document icon on 10.10.3. Maybe a document type registry thing? Haven’t heard anyone else has the problem either. I’ll leave this open though, at least until I can see the small icon myself.

**Comment by ptzz** [comment]
Ok, there are definitely issues with the Finder icon handling on Mac. I tested associating .md files with MacVim (not permanently of course :wink:). This resulted in Finder icons changing to Vim icon, but only if I set icon size to greater than 12.

**Comment by Morane** [comment]
Tip : When a md icon is blank (with a pen inside), at any size, just do it :
 
* Select it
* Type Cmd I (for informations)
* Copy icon
* Paste right now this blank icon at the same place

Blue Macdown icon is back ! In fact, if you copy a blank icon in Preview, you just see different sizes of a blue icon. I don't know why, but OS X has a problem with md files icon (Macdown, Txts, etc.)

Best
