### ISSUE TITLE
markdown parser consider Table null content as |

### ISSUE THREAD

**Issue by ipfans** [uranusjr/macdown#321]
When write a table like this:

```
|headline1|headline2|
|:-------|:-------|
|123||
```

It should be:

|headline1|headline2|
|:-------|:-------|
|123||

But it is:

|headline1|headline2|
|:-------|:-------|
|123|\||

So maybe this is a parser bug?

**Comment by ipfans** [comment]
同样的问题在三列时更明显

```
|headline1|headline2|headline3|
|:-------|:-------|:-----|
|123|||
```

就变成了

|headline1|headline2|
|:-------|:-------|
|123|\|\|||

**Comment by joeles** [comment]
It should be noted that adding space between the pipes in the markdown does not help hint the parser to do the right thing.

```
|headline1|headline2|
|:--------|:--------|
|123      |         |
```

Still renders broken.

|headline1|headline2|
|:--------|:--------|
|123      |   \|      |

**Comment by ipfans** [comment]
@uranusjr hi, hoedown has released 3.0.3 fixed this problem, is any plan macdown upgrade to the new hoedown engine?

**Comment by uranusjr** [comment]
Did’t realise 3.0.3 is already on CocoaPods. I’ll issue an update asap.

**Comment by ipfans** [comment]
thx for your works

**Comment by uranusjr** [comment]
Just want to mention 0.4.5.1 is just out. The fix should be contained.
