### ISSUE TITLE
AppleScript support

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/macdown#324]
Imported from Gitter.

I seem to read somewhere that Apple might be ditching AppleScript in favour of JavaScript in the future. So this might be taken into account, too.

**Comment by Jmuccigr** [comment]
Huh. Haven't heard about that. You referring to this kind of thing:

http://lists.apple.com/archives/applescript-users/2014/Jun/msg00004.html

I doubt AS is going away anytime soon.

If MacDown would just accept basic AS stuff like 

    set fpath to (path of document 1) as text

That would be great.

**Comment by Jmuccigr** [comment]
Any further thoughts on this? The ability to cover even the standard suite (copy, paste, open, close) would be very helpful.

**Comment by uranusjr** [comment]
One minor note on the AppleScript API: I decided to left out the `path` property since it has been deprecated by Apple since long ago. The proper way now is to get a file handle first:

~~~applescript
set f to file of the first document
~~~

And then convert it to string

~~~applescript
set fpath to f as text
~~~

And, to get the POSIX path (I usually want this instead):

~~~applescript
set ppath to POSIX path of fpath
~~~

**Comment by Jmuccigr** [comment]
This is great. Can't wait for a new build so I can try it out.
