### ISSUE TITLE
Saving documents with non-.md extensions overrides file name

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/macdown#326]
[From Twitter](https://twitter.com/homoky/status/582234592733712385).

Video demo http://soubory.homoky.cz/Screen-Recording-2015-03-29-19-34-15-rS62wb0qny/

**Comment by getaaron** [comment]
This video 404s. Any idea what the bug was or if it's still there?

**Comment by uranusjr** [comment]
Not sure. I should have made more notes on this. Closing.
