### ISSUE TITLE
Add donate link

### ISSUE THREAD

**Issue by fulldecent** [uranusjr/macdown#337]
The Mac world is dying for a great markdown editor.

Please add a donation link to the bottom with Gratipay or whatever. We want to keep you motivated for moving this project forward!

**Comment by uranusjr** [comment]
[There’s a Paypal form on the website](http://macdown.uranusjr.com/faq/#donation). Last time I check, none of those hippy tipping services support payouts outside of the US, so for now, Paypal it is. Should I put this somewhere more visible?

**Comment by ohthetrees** [comment]
Absolutely. It should be prominently on the front page. There should also be a "Donate" menu item in the app. Also, I think a one-time splash screen should pop up asking for a donation after the 10nth app launch or 30 days passes, whichever comes second. Don't be shy about this, you are doing a ton of work, these changes would be not very intrusive, and you deserve it.
