### ISSUE TITLE
Command Line Mode?  

### ISSUE THREAD

**Issue by jeeftor** [uranusjr/macdown#346]
I don't know if this exists currently but I would love a way to do the HTML Export function via command line.  Any chance for a command line functionality?

**Comment by miketoth** [comment]
You might want to look at [pandoc](http://pandoc.org/) if you haven't already. It can convert markdown to pretty much anything and works from the command-line.

**Comment by uranusjr** [comment]
Pandoc is a good choice, and free (in many ways). I would prefer not to re-invent the wheel, especially if such a brilliant one exists.
