### ISSUE TITLE
Just wondering if there's a spelling checker in MacDown? doesn't seem so - double checking ...

### ISSUE THREAD

**Issue by charles-cai** [uranusjr/macdown#355]

**Comment by Jmuccigr** [comment]
Edit menu
Spelling and Grammar

Make sure the desired lines are checked.

**Comment by saulspatz** [comment]
Just started using MacDown and it's great.  I plan to use it mainly for writing math, though, and it would be nice if it were possible to turn off spelling checking in the math formulas.  Alternatively, the Tex symbols like \frac and \infty could be added to the dictionary, but that's an inferior solution.  As it is, there are so many words underlined as misspelled that it isn't easy to pick out the real errors.

**Comment by franklinyu** [comment]
@saulspatz That deserves a stand-alone issue!

**Comment by saulspatz** [comment]
@franklinyu I'm glad you agree with me, but I don't know what as stand-alone issue is, I'm sorry to say.  If you're suggesting that I ought to create an issue somehow, perhaps you could take care of it?
