### ISSUE TITLE
Indentation doesn't support emphasising syntax  

### ISSUE THREAD

**Issue by romanvbabenko** [uranusjr/macdown#357]
In opposite to Mou, Macdown doesn't render emphasising syntax inside indentation block. 
Not sure, it's a feature or a bug.

**Comment by uranusjr** [comment]
Could you provide some examples?

**Comment by romanvbabenko** [comment]
Oops Mou behaviour is the same, but look

!https://www.evernote.com/shard/s68/sh/e91c283a-fcee-4936-9069-3e038d877866/5ab59940dfe207022f50820f78824a6e/res/ec4d92b1-249e-4031-ac96-6d23c2038762/skitch.png?resizeSmall&width=832!

I expected that 4 spaces indented block will be appeared like quota based one. Do I wish too much? :-)

**Comment by ohthetrees** [comment]
Before space indent indicates a code block. Inside of code block all characters should be faithfully reproduce.


Cedar

**Comment by romanvbabenko** [comment]
Got it. My fault. Thanks.
