### ISSUE TITLE
Lines don't break after full screen preview

### ISSUE THREAD

**Issue by ladislas** [uranusjr/macdown#360]
First let me thank you for this awesome piece of work! I've been using Mou for quite sometimes now but always thought it was lacking some basic functions. Now I know where to find them ;)

Anyway, I was playing with MacDown to see how my large files would render and I tested the full screen preview mode by hiding the editor pane. After restoring the editor pane, the lines don't automatically break and thus I can't read the file anymore.

Here is a screenshot to show you what I mean.

![screenshot 2015-04-30 10 01 33](https://cloud.githubusercontent.com/assets/2206544/7408756/64047770-ef20-11e4-92bc-1a3341e2fd01.png)

Maybe it's me and I've done something wrong! :)

**Comment by wkjagt** [comment]
Not just you, same here :-) But you're right, this tool is great.

**Comment by uranusjr** [comment]
This might be the same problem as #289, which was fixed by #339. I will issue a pre-release soon (probably tomorrow if things go as planned) so that you could confirm whether the bug is really fixed.

**Comment by uranusjr** [comment]
Alright, I’ve [published the pre-release](https://macdown.uranusjr.com/history/testing/#version_642). You can use the download link there, or switch to pre-release in the preferences and update automatically. Please report if this resolves your problem.

**Comment by ladislas** [comment]
@uranusjr yes it works now!

But I have a new issue: when playing with hiding and restoring preview ans editor panes, I find myself not being able to have both at the same time.

Do you want me to open a new issue for this?

**Comment by uranusjr** [comment]
Yes it would be better to make this a new issue. Did you try the “Left 1:1 Right” option? This should force the layout to the original state.

(Closing this as fixed.)

**Comment by ladislas** [comment]
> Did you try the “Left 1:1 Right” option? This should force the layout to the original state.

Yes it works, thanks a lot! :)

**Comment by wkjagt** [comment]
Fixed it for me too! Thanks a lot!
