### ISSUE TITLE
About keypress sound

### ISSUE THREAD

**Issue by beanlee** [uranusjr/macdown#376]
What a Wonderfull tool !
Can It Increased the keypress sound like a Typewriter?(´･_･`)

**Comment by uranusjr** [comment]
This is out of the scope (I know Mou has it).

I highly recommend [this utility](http://bbs.feng.com/read-htm-tid-9003484.html) for typing sounds. Works throughout OS X.

**Comment by beanlee** [comment]
thanks, got it
