### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by quentin-chen** [uranusjr/macdown#380]
Why don't u take [TOC] into consideration.

**Comment by ohthetrees** [comment]
Under the "View" menu, select "Renders TOC". That should do it, though in my opinion, that option should be in the preferences with all the other render options.

**Comment by Mark-L6n** [comment]
+1 for putting this in the preferences panel—that's where I was looking for this, too.

**Comment by iparr** [comment]
Note for anyone as lost as I was, on the latest version (0.5) this has been moved to the preference section as suggested above.

It's in Preferences > Rendering > "Detect table of contents token"

**Comment by uranusjr** [comment]
Oops, obvious I forgot to close this. Relevant commit: a05e338
