### ISSUE TITLE
Table with one or more blank header

### ISSUE THREAD

**Issue by NicosKaralis** [uranusjr/macdown#386]
This are some tables that should render with a header row, but with no contents inside the header cells

    |    |    |
    |---:|:---|
    |`master`|master|
    |`dev`|dev|

|    |    |
|---:|:---|
|`master`|master|
|`dev`|dev|

    |    | Anything   |
    |---:|:---|
    |`master`|master|
    |`dev`|dev|

|    |  Anything  |
|---:|:---|
|`master`|master|
|`dev`|dev|

Instead this is the output I'm getting in MacDown

![image](https://cloud.githubusercontent.com/assets/627404/8107270/87fcdd74-101e-11e5-8a7b-c4dd04cdcdeb.png)

**Comment by uranusjr** [comment]
This should be fixed after 0.4.5.
