### ISSUE TITLE
Hiding editor pane then showing it again loses line wrapping

### ISSUE THREAD

**Issue by tommorris** [uranusjr/macdown#390]

**Comment by uranusjr** [comment]
What version of MacDown are you using?

**Comment by tommorris** [comment]
@uranusjr: Version 0.4.4.1 (624).

I've just updated to Version 0.4.5.1 (647) and it seems to have resolved the issue. Sorry for the distraction.

**Comment by uranusjr** [comment]
Good to know. :)

I honestly don’t remember fixing anything that would resolve this issue, so feel free to reopen this if it ever happens again.
