### ISSUE TITLE
can't open more than one file

### ISSUE THREAD

**Issue by timotheecour** [uranusjr/macdown#392]
~/Applications/MacDown.app/Contents/SharedSupport/bin/macdown file1.md
#opens it
~/Applications/MacDown.app/Contents/SharedSupport/bin/macdown file2.md
#doesn't do anything

**Comment by timotheecour** [comment]
on the other hand this works, but I read somewhere in the docs that we should use SharedSupport/bin/macdown for the command line version.

~/Applications/MacDown.app/Contents/MacOS/MacDown file1.md &
~/Applications/MacDown.app/Contents/MacOS/MacDown file2.md &

**Comment by timotheecour** [comment]
[i'm on osx] 
...except that COMMAND + BACKTICK doesn't cycle through macdown windows in that case, so it's kind of broken

**Comment by uranusjr** [comment]
Hmm, yes, I can reproduce this. Wonder how this bug went unnoticed for such a long time. Thanks for the report!
