### ISSUE TITLE
Reload action looses markdown rendering

### ISSUE THREAD

**Issue by timotheecour** [uranusjr/macdown#394]
to reproduce:
~/Applications/MacDown.app/Contents/MacOS/MacDown some_file.md &
the file opens in macdown and renders in 2 panes; the right correctly shows the md file being rendered.
Then right click (shows Reload button); click that reload button; 
now instead of reloading, it shows raw text on the right pane instead of rendering it.
That happens regardless of whether file actually changed on disk or not

**Comment by uranusjr** [comment]
Should be fixed in cd913be with #412.

**Comment by uranusjr** [comment]
Just a side note: With 0.4.6 it is not recommended to open a new file with the following command instead:

    ~/Applications/MacDown.app/Contents/SharedSupport/bin/macdown some_file.md

See this [wiki entry](https://github.com/uranusjr/macdown/wiki/Advanced-Usage#open-a-file-in-macdown-from-terminal) for more information.
