### ISSUE TITLE
[TOC] shows title (should only show sections, ie ones with '##' or more)

### ISSUE THREAD

**Issue by timotheecour** [uranusjr/macdown#397]
unless i'm missing something and there's another way to write title than to use '#some title' ?
(eg " %title is used in pandoc, cf http://stackoverflow.com/questions/17097894/markdown-tag-for-document-title but doesn't work in macdown)

EDIT: just saw https://github.com/uranusjr/macdown/issues/391 ; the best outcome if is TOC keeps showing likes with '#' >=1  but allows %title

**Comment by uranusjr** [comment]
Closing as duplicate then?
