### ISSUE TITLE
need recommendation for apps which can navigation files 

### ISSUE THREAD

**Issue by huyingjie** [uranusjr/macdown#406]
Macdown is my main tool to take notes. I have created thousands of notes. Usually there are a lot of notes in each folder and I hope that there is an easy way to view/navigate the notes. 

I hope I can find a way to view the notes in the same way with software, like evernote, sublime,  ulysses, and Quiver. They use a three-column arrangement. It is better to have four-column arrangement. 

column 1: folder structure

column 2: file list

column 3: macdown editor pane

column 4: macdown preview pane

Here are the examples of evernote, sublime, and ulysses, and Quiver. 

![](http://blog.evernote.com/files/2011/03/evernote_web_new8.jpg)

![](http://i.stack.imgur.com/yLTNs.png)

![](http://3.bp.blogspot.com/-Aoi91R9RPnE/VAu-vtRA3RI/AAAAAAAAGXE/kvspVY6Uptg/s1600/u3-window.png)

![](http://happenapps.com/images/quiver/quiver0.png)

**Comment by uranusjr** [comment]
MacDown is a text document editor, not a note management app, nor a code editor. This has been discussed many times, and ideas tossed around. Please refer to existing relevant issues.

Closing as duplicate.
