### ISSUE TITLE
Line numbers in code blocks only work with a valid language label

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/macdown#410]
Imported from #341.

This only works if you supply a valid language name. So line numbers show for this:

    ~~~bash
    cd /etc
    ls
    ~~~

But not this:

    ~~~
    cd /etc
    ls
    ~~~

---

This is probably caused by the plugin hooks from Prism. My guess is that the plugin is run when highlighting succeeds. If no language is specified, Prism is not run at all, so the plugin is not run. If an invalid language name is given, highlighting fails, and the plugin is not run.

Possible fixes:

1. Patch the plugin. Would upstream accept this, or do we need to fork?
2. Supply a “default” language that is applied to invalid or null language names (probably `language-null`?). This will make highlighting work, thus always triggering the plugin. This feels like hacky though.

**Comment by NickVolynkin** [comment]
And not this:

    <4 space indent> code-code-code
    <4 space indent> some-more-code

**Comment by uranusjr** [comment]
This turns out to be a two-part problem. MacDown currently processes code blocks with a language name through the highlighter (which includes the line numbering plugin). Four-space-indent blocks and unnamed blocks are thus not processed, and do not get line numbers. I have made amends for this, and now all code blocks should be processed by Prism.

But the above change is not enough. Although the blocks are processed, limitations in Prism’s plugin system still prevents the line number plugin being run. This problem is now in discussion in PrismJS/prism#645, and we should be able to resolve this after that is fixed.

I’m marking this as upstream problem instead, since we have done all we could here. I will issue a bug-fix release as soon as upstream fix is available.

**Comment by NickVolynkin** [comment]
Just updated MacDown to a new version. Made a test with both  4-space-indent and ~~~:

    <4 space indent> cd /etc
    <4 space indent> ls
    
    ~~~
    cd /etc
    ls
    ~~~

Both look like this, with checkbox on:

<img width="461" alt="screen shot 2015-08-13 at 17 13 22" src="https://cloud.githubusercontent.com/assets/8015154/9248578/4d8e3536-41d6-11e5-826a-47997d7beb20.png">

With checkbox off (no line numbers are expected)

<img width="469" alt="screen shot 2015-08-13 at 17 13 41" src="https://cloud.githubusercontent.com/assets/8015154/9248585/5f5c2156-41d6-11e5-8eb1-7e5901a0c443.png">

The `~~~bash` syntax is fine, it shows line numbers.

Am I doing anything wrong?

**Comment by uranusjr** [comment]
The new version was release a few days ago, and does not include this. (Sorry.) I’m still working on some other issues, but a new version should be available before the end of this month.

If you want this feature right now, you can crack open the .app bundle, and replace both `components/` and `plugins/` directories inside `MacDown.app/Contents/Resources/Prism` with [files in this archive](https://github.com/PrismJS/prism/archive/gh-pages.zip).

**Comment by NickVolynkin** [comment]
Oh, no problem. I saw a line about line numbers in the release notes and thought that the full feature is implemented in that version. 

I've just updated to v. 0.5 (670) and checked the formatting. It works! Thank you )
