### ISSUE TITLE
Highlight spell check errors

### ISSUE THREAD

**Issue by nhoizey** [uranusjr/macdown#411]
I know there is some sort of spell check because a right click on an error let me fix the error, but MacDown doesn't show any hint of this error. It would be greaaaat! ;-)

**Comment by uranusjr** [comment]
There is a “Check Spelling While Typing” option under Edit → Spelling and Grammar. Red dashed lines appear under misspelled words if you check it. Is this what you want?

(Other options in the same menu might be useful too. These functionalities are actually provided by OS X.)

**Comment by nhoizey** [comment]
OMG, sorry, I didn't know it is done directly on the OS level.

Thanks a lot for your help!
