### ISSUE TITLE
Rendering breaks when clicking on an empty link

### ISSUE THREAD

**Issue by phunkfoo** [uranusjr/macdown#412]
Not entirely sure how to classify this issue - But it would seem that an empty link:  
```markdown
[Title]()
```  
will display correctly, but break the rendering when clicked on. The rendering pane reverts to a plain text view of the text.  

<img width="1920" alt="screen shot 2015-07-21 at 20 44 09" src="https://cloud.githubusercontent.com/assets/7114750/8810912/4841cd0c-2fea-11e5-9fea-5093f7892a75.png">
<img width="1920" alt="screen shot 2015-07-21 at 20 44 18" src="https://cloud.githubusercontent.com/assets/7114750/8810915/4aa372c6-2fea-11e5-875b-dcee5a85b465.png">
<img width="1920" alt="screen shot 2015-07-21 at 20 44 27" src="https://cloud.githubusercontent.com/assets/7114750/8810919/4ca803f2-2fea-11e5-84d8-6ff6227ca677.png">
<img width="1920" alt="screen shot 2015-07-21 at 20 44 30" src="https://cloud.githubusercontent.com/assets/7114750/8810922/4e9b0c18-2fea-11e5-8521-7b3afbd89ddd.png">

**Comment by Jmuccigr** [comment]
This is a weird one for me. I had to play around a bit to get the click to cause the problem. That is, it didn't  work right away, but only after some editing of the document. Once it started though, it kept happening.
