### ISSUE TITLE
No strike possible

### ISSUE THREAD

**Issue by Erowlin** [uranusjr/macdown#422]
Hello, 

Currently, I'm not able to do any strike on my text. I tried the syntax ~~Scratch me~~ (surrounding the text with ~~), but it won't work (the ~~ characters are not interpreted in the preview) . 

I don't know if it's a specific bug or not. 

I'm using the latest Version 0.4.6 (657)

Thx.

**Comment by uranusjr** [comment]
Did you check the “Strikethrough” box in the preferences. This works for me.

**Comment by Erowlin** [comment]
It worked, thank you ! I wonder why those options are not enable by default ?
