### ISSUE TITLE
Wrong preview if using new lines in lists

### ISSUE THREAD

**Issue by Pimpnase** [uranusjr/macdown#425]
If you use lists by using the dash and you press enter, the preview-panel shows the next (empty) line as a headline with an underline.

Just type a line "- test1" and press enter and you see the result shown in the attached image.
![md-format-failure](https://cloud.githubusercontent.com/assets/870589/9252560/43cdc004-41d9-11e5-9656-c6ea4ea8b7ac.png)

**Comment by uranusjr** [comment]
According to the original Markdown spec, list items cannot be empty, so this is a malformed document. What happens in this kind of situations is undefined, and [different implementations do things differently](http://johnmacfarlane.net/babelmark2/?text=-+One%0A-+Two%0A-). I admit the parser is a bit cruel on this one, but it is not wrong.

This is not a bug. You need to delete the trailing `-`.
