### ISSUE TITLE
Nested strong/emphasis rendering incorrectly

### ISSUE THREAD

**Issue by endersstocker** [uranusjr/macdown#426]
If strong and emphasized text are nested, the generated HTML is incorrect.

For example, this:
~~~
*foo **bar***

**baz *qux***
~~~

renders:

> \*foo **bar**\*
>
> <strong>baz \*qux\*</strong>

instead of:

> <em>foo <strong>bar</strong></em>
>
> <strong>baz <em>qux</em></strong>

**Comment by uranusjr** [comment]
This is a known issue (#260; you can also read issues linked in my comment there if you’re interested in technical details). There are efforts in developing a new parser that solves this, but that is not nearly ready, and unfortunately I can’t fix this without breaking lots of other features. I’m closing this as a duplicate, but this will be addressed once the new parser is developed.

FWIW, did you notice GitHub renders your examples into even worse results than MacDown? This is really difficult to get right.
