### ISSUE TITLE
[Feature request] When doing lists, indent on <enter><tab>

### ISSUE THREAD

**Issue by Joshfindit** [uranusjr/macdown#430]
Currently, when making an unordered or ordered list, MacDown responds like:

`* item` `<enter>` = 

    * item
    * 

This is excellent for making lists, as it allows us to just keep typing.

When we want to have an indented list item like:

    * item
    * item
        * indented item

We would expect to type `* item` `<enter>` `<tab>` `indented item`, however MacDown currently responds like:

    * item
    * item
    *     indented item

Similarly, when doing  `2. item2` `<enter>` `<tab>`  it would be nice to automatically generate:

    1. item1
    2. item2
        1. item2.1

**Comment by uranusjr** [comment]
We tried this a while ago, but it doesn’t work s well because it’s a bit hard for the program to guess what the user wants. It is possible, but not good enough at the moment. For now my recommendation is to use  <kbd>⌘</kbd>+<kbd>]</kbd> to indent instead.

**Comment by uranusjr** [comment]
Closing as duplicate. See #161.
