### ISSUE TITLE
Opening MacDown with xargs only shows 1 doc

### ISSUE THREAD

**Issue by getaaron** [uranusjr/macdown#443]
Reproduction steps:

At the command line in a directory of Markdown files, I run:

    $ grep -ril "hello" . | xargs open

To open all docs with the text "hello".

Expected behavior: I expect all files listed in `grep -ril "hello" .` to appear in separate windows.

Actual behavior: MacDown displays just one file. However, if I <kbd>⌘</kbd>-<kbd>tab</kbd> to another app and back, all of the windows appear.

I'm using MacDown Version 0.5 (670).

**Comment by uranusjr** [comment]
I’m getting the expected behaviour with 0.5.1. (Haven’t tested 0.5.)

**Comment by getaaron** [comment]
Works fine for me in Version 0.5.1 (679). Thanks!
