### ISSUE TITLE
Scroller lock not working?

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/macdown#447]
The scroller position lock-restore does not seem to work anymore. The preview pane now jumps back to the beginning of the document after re-rendering.

Relevant code:
https://github.com/uranusjr/macdown/blob/master/MacDown/Code/Document/MPDocument.m#L987

**Comment by uranusjr** [comment]
Seems to fix itself after fixing the `NSNumber` error.

@JanX2 could you verify this fix does not change the behaviour?
https://github.com/uranusjr/macdown/commit/53f3a46dba67e7461d76ea350167db8c19c2ed5f

**Comment by JanX2** [comment]
This won’t change behavior on X86-64, because double == CGFloat. I have seen improper treatment of types biting people whenever Apple transitions to new hardware and so I try to do things by the book. In this case I missed checking for the return value of `CFNumberGetValue()` and setting `fontSize` to 0.0 in the `false` case. That would be the correct solution.

**Comment by uranusjr** [comment]
Ah, that makes sense. I had doubts mixing `double` and `CGFloat` too, and you confirmed my worries.

Will this implementation be preferable then?

~~~objc
NSNumber *fontSizeNum = self.preferences.editorBaseFontInfo[@"size"];
if (!fontSizeNum)
    return;
CFNumberRef fontSizeNumCF = (__bridge CFNumberRef)(fontSizeNum);
CGFloat fontSize;
if (!CFNumberGetValue(fontSizeNumCF, kCFNumberCGFloatType, &fontSize))
    return;
const CGFloat defaultSize = 14.0;
CGFloat scale = fontSize / defaultSize;
// ...Skipped.
[self.preview setPageSizeMultiplier:scale];
~~~

**Comment by JanX2** [comment]
Looks good to me. :)

**Comment by uranusjr** [comment]
After some consideration I decided to stick with `-doubleValue`. This is more permissive in cases that the size is stored as an `NSString` instead of `NSNumber` (which is possible, I’m afraid).

I’m putting faith in Apple that `CGFloat` should at least be some sort of floating-point type. If it’s `double` everything is fine; if it’s `float`, automatic down-casting will happen. Even if it becomes `long double`, the error-rounding should be minimal.

**Comment by JanX2** [comment]
Ok. :)
