### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/macdown#448]
The main problem is that `macdown-cmd`’s empty Pod-resource-copying step does not work. I need to manually delete it to perform release builds. Cocoapods had fixed this, but we’re stuck at 0.34.4 for handlebars-objc, so I’ll need to come up with some hacks to work around that.

Xcode 7 really broke a lot of things.

**Comment by fionser** [comment]
Is this error `ld: library not found for -lPods-macdown-cmd` ??

**Comment by uranusjr** [comment]
I’m not sure; the error happens only when I run the [build script](https://github.com/uranusjr/macdown/blob/master/Tools/build_for_release.py), not in Xcode or on Travis.

I just tried the build script again, and surprisingly it runs successfully(!?) now on Xcode 7.1. I’m closing this.

**Comment by fionser** [comment]
actually, this error happens from the Xcode 7.1....

**Comment by uranusjr** [comment]
It’s a different issue then. I’m not getting that after upgrading to 7.1. What versions of Ruby and Cocoapods are you using?

**Comment by urmyfaith** [comment]
I am using

``
$ pod --version
0.39.0
``

when turn this pod to MRC, works now.

![](http://ww3.sinaimg.cn/large/6b288462gw1exwfhsjv2rj20xc0ip796.jpg)

**Comment by fionser** [comment]
@urmyfaith thanks a lot!
