### ISSUE TITLE
Not rendering after El Capitan upgrade

### ISSUE THREAD

**Issue by andrewresearch** [uranusjr/macdown#452]
Macdown is no longer rendering after upgrading to El Capitan. It will export OK, but not show the rendered preview.
Deleting preferences appears to work, but then open another file and rendering stops.

**Comment by uranusjr** [comment]
Are you using MacDown 0.5 or 0.5.1?

**Comment by andrewresearch** [comment]
0.5.1

**Comment by uranusjr** [comment]
Hmm, that’s weird. I’ll look into this.

**Comment by funkhou9** [comment]
:+1:

**Comment by uranusjr** [comment]
Just did some preliminary investigation, and it seems like the new App Transport Security policy is the culprit. It blocks the MathJax scripts from loading, and thus hangs the whole webview. **Disabling math rendering should fix the issue.**

Automatic updating is also broken for the exact same reason. Looks like I’m going to have a very busy weekend.

**Comment by andrewresearch** [comment]
OK Thanks Tzu-ping Chung. For some of my writing I can live without MathJax for now.
Cheers.

**Comment by uranusjr** [comment]
@andrewresearch @funkhou9 Could you help me test out whether this build resolves the problem?

http://d.pr/f/17zS6

**Comment by funkhou9** [comment]
Yes, now rendering with math support! Thank you very much.

**Comment by andrewresearch** [comment]
Yes, all good - thank you.

**Comment by uranusjr** [comment]
Fixed in d5db85e. 0.5.2 coming in a minute!
