### ISSUE TITLE
Rendering halts when "TeX-like math syntax" is turned on

### ISSUE THREAD

**Issue by rsy96** [uranusjr/macdown#455]
Once I ticked the option of "TeX-like math syntax", the rendering of markdown stops, even when I don't input any math in the document. I thought MacDown was blocked waiting to download MathJax, but I waited half an hour with an Internet connection and nothing changed. I also manually verified that I could connect to `cdn.mathjax.org`.

I am using MacDown 0.5.1 (679) on El Capitan.

**Comment by uranusjr** [comment]
See #452. This is fixed in 0.5.2.

***Note:*** *Due to a related issue under El Capitan, the built-in updating mechanism will not work. El Capitan users with MacDown 0.5.1 will need re-install the application to upgrade correctly.*
