### ISSUE TITLE
Crashed after typing $\\($

### ISSUE THREAD

**Issue by b-z** [uranusjr/macdown#460]
After I typing $\\\\($ in macdown, it crashed...

Mine is version 0.5.2 (689)

\_(:з」∠)\_

**Comment by uranusjr** [comment]
Strange, I cannot reproduce this. Could you give me your settings (screenshot or something) and the content of the crash dialog (if any)?

**Comment by b-z** [comment]
There weren't any crash dialogs yesterday(just stop responding)
Well, I've restarted my Mac and that problem doesn't occur any more. = =

**Comment by uranusjr** [comment]
Well I guess that’s good news…? Hope this won’t happen again.
