### ISSUE TITLE
Some images fail to load in render, e.g. images in help.md

### ISSUE THREAD

**Issue by torarnv** [uranusjr/macdown#465]
>  Seems like it’s caused by the new security features in 10.11. It causes problems with some providers (e.g. Amazon CloudFront, which hosts the images in help.md). - @uranusjr

**Comment by walkingway** [comment]
I have a same problem

**Comment by lcafaro** [comment]
Confirmed

![screen shot 2015-10-13 at 8 05 17 a m](https://cloud.githubusercontent.com/assets/13108002/10447055/2aac1e22-7181-11e5-9807-7b9d0cff2c2e.png)

**Comment by getaaron** [comment]
@torarnv @walkingway @lcafaro Check my pull request - it resolved the issue for me.

**Comment by lcafaro** [comment]
@getaaron thank you, confirmed working.

![screen shot 2015-10-15 at 4 14 26 a m](https://cloud.githubusercontent.com/assets/13108002/10503125/4516ea58-72f3-11e5-941b-3bf9f1b2eb89.png)

**Comment by marlowe310** [comment]
How should I implement the changes to the plist to get this working? I tried editing my plist directly, but that seems to damage MacDown and make it not open. I also tried replacing it entirely with getaaron's plist - that changed the name of the app. Is there a working build with this change included already?

Thanks much.

**Comment by lcafaro** [comment]
@marlowe310 you just need to add these lines in ```NSAppTransportSecurity```:

```
		<key>NSAllowsArbitraryLoads</key>
		<true/>
```
Here's the original plist with those two lines added in, if you want to diff it with yours: https://gist.github.com/lcafaro/9384f73c5642e978baf2

**Comment by marlowe310** [comment]
@lcafaro thanks VERY much -- replacing the plist with the one you linked to worked like a dream. Really appreciate you helping me out and so quickly.

**Comment by lcafaro** [comment]
You're welcome! Let's hope this gets merged to master soon.

**Comment by uranusjr** [comment]
Closing this in favour of #468.
