### ISSUE TITLE
Crash on Quit

### ISSUE THREAD

**Issue by pauldknox** [uranusjr/macdown#470]
I've found that  MacDown crashes / hangs every time I try to close it. I'm running OS X 10.11.

**Comment by uranusjr** [comment]
Can you provide the crash dialog?

**Comment by pauldknox** [comment]
HI, 

I’m sorry, no. I’ve cleared it since I told you. 

Cheers, 

Paul K.

**Comment by uranusjr** [comment]
I’m closing this for now, but this happens to you again in the future you can just reopen this and attach the crash report.
