### ISSUE TITLE
Action on highlighted text introduces other text

### ISSUE THREAD

**Issue by Jmuccigr** [uranusjr/macdown#475]
I've just seen this problem with the block quote function, where it grabs preceding text, but I'm pretty sure it happens with other commands.

To re-create:

Highlight any part of the second line of this text (= "two"):
```
one
two

```

The result is:
```
one
> one

```

The same number of letters are selected in the new "one" as were selected in the line prior to the command.

**Comment by uranusjr** [comment]
Note: This happens only when there is a third line (or more). This does not happen if `two` is at the very end of a document.

**Comment by Jmuccigr** [comment]
This is great (and I love the comment in #565e638!). Any idea when you'll release a new version with this fix?
