### ISSUE TITLE
bug：到处文件后显示错误

### ISSUE THREAD

**Issue by zyl54586** [uranusjr/macdown#477]
比如一串很长的字符串abc_def_ghi_jklmn，转换成PDF或者HTML后下划线都消失了。

**Comment by uranusjr** [comment]
You need to either

1. Uncheck “Intra-word emphasis” (not a good idea when writing in Chinese)
2. Use escapes, e.g. `abc\_def\_ghi\_jklmn`
3. Use the code format, e.g. `` `abc_def_ghi_hklmn` ``
