### ISSUE TITLE
Bug? - Image Links not rendering in Preview pane on El Capitan, v0.5.2

### ISSUE THREAD

**Issue by markedwardmurray** [uranusjr/macdown#479]
<img width="953" alt="screen shot 2015-10-26 at 4 59 15 pm" src="https://cloud.githubusercontent.com/assets/10505365/10742423/7cb827c4-7c03-11e5-96dc-5a5190acece8.png">

I recently upgraded my OS to El Capitan. Despite running MacDown v0.5.2 I'm experiencing an issue in which the preview pane does not render any valid image links (they do appear correctly when viewed on GitHub). Could this be due to any preferences that I can change, or did El Capitan break it?

**Comment by gilbarbara** [comment]
👍

**Comment by huluqiu** [comment]
same problem

**Comment by gechr** [comment]
+1

**Comment by tianskylan** [comment]
+1

**Comment by markedwardmurray** [comment]
Thank you!
