### ISSUE TITLE
Won't propose reload if file change outside of MacDown

### ISSUE THREAD

**Issue by anirul** [uranusjr/macdown#48]
If the file you are editing change outside the program don't see the changes and will overwrite them!

**Comment by diimdeep** [comment]
Don't work in 0.4.2.
I think it should prompt to whether to reload only if there is some unsaved changes in editor, otherwise just reload.

**Comment by uranusjr** [comment]
This is not merged to the official releases yet because there are still multiple issues I want to address first, the most important one being it not working when autosave is turned off. Unfortunately it might not be nearly production-ready in near-term future.

**Comment by ohthetrees** [comment]
In my opinion, BBedit handles it perfectly.

If the open file in BBEdit _does not_ have any unsaved changes, and the file changes on disk, then BBEdit silently refreshes. If the open file in BBEdit _does_ have unsaved changes, then it asks what to do.

![screen shot 2015-02-04 at 1 41 03 pm](https://cloud.githubusercontent.com/assets/1884467/6050388/f23f559a-ac73-11e4-8c98-0d9a5c05fe10.png)

**Comment by ohthetrees** [comment]
If this feature is far from ready, what about a "reload file from disk" menu item to tide us over? At the moment, I'm always closing and re-opening files, just to make sure that any changes to disk are not over-written.

**Comment by adrenth** [comment]
I ran into the same issues (changes made elsewhere were overwritten). Have you @uranusjr addressed the issues mentioned earlier? I found some related issues, but it seems you still struggling with this feature?

**Comment by uranusjr** [comment]
I didn’t find a straightforward solution, and really haven’t had much time to look deeper into this. Go  ahead if you want to have a shot at it; I’ll be more than happy to accept a patch. :)

**Comment by Jmuccigr** [comment]
I agree that BBEdit handles this well.

**Comment by donnemartin** [comment]
>If this feature is far from ready, what about a "reload file from disk" menu item to tide us over? At the moment, I'm always closing and re-opening files, just to make sure that any changes to disk are not over-written.

:+1:
