### ISSUE TITLE
Feature request: Surround selected text with regularly used formatting

### ISSUE THREAD

**Issue by aharish** [uranusjr/macdown#480]
Is there any possibility of surrounding the selected text with say, a `**` or a `()`? 

I know that Writeily Pro for Android does this, and it's pretty simple, so I was wondering of this was possible? I'm completely new to OS X development. I just use OS X *for* development LOL

**Comment by Jmuccigr** [comment]
That's what the various menu commands under "Format" do already. "Bold" will get you ```**text**```. Nothing for the parentheses though, since that's not markdown formatting, unless you mean adding a link, which is command-shift-K

**Comment by uranusjr** [comment]
Actually there’s a “Auto-complete matching characters” feature in the Editor preferences. Parentheses and asterisks work, as well as some others.
