### ISSUE TITLE
Single and double quotes are replaced with "smart quotes"

### ISSUE THREAD

**Issue by vfonic** [uranusjr/macdown#481]
Hi,

I've changed some settings and now sometimes when I insert ' or ", it changes to those curved quotes. This is really bad, especially when I use MacDown to write code blocks that are then incorrect due to wrong quote signs.

I use MacDown 0.5.9 (689), here are my prefs:
<img width="513" alt="screen shot 2015-10-27 at 14 49 43" src="https://cloud.githubusercontent.com/assets/67437/10761598/0705fc9c-7cba-11e5-83e1-c6f87b9c1c9d.png">

**Comment by Jmuccigr** [comment]
In the preview pane or in the editor pane? For me, the curly quotes show up in the preview, but not if I put the text in code fence.

**Comment by vfonic** [comment]
Here's the file I typed:
```
let me try

`this ‘quote’ is wrong`
```

I typed backtick ` around the block and single quotes ' around quote word.

**Comment by uranusjr** [comment]
That’s an OS X thing. You need to turn this off.

![screen shot 2015-10-28 at 8 03 07 am](https://cloud.githubusercontent.com/assets/605277/10776247/a7c83d30-7d4a-11e5-8339-6a10650a5ad5.PNG)

**Comment by vfonic** [comment]
It worked! Thanks!
