### ISSUE TITLE
handlebars fails to build even after following build instructions

### ISSUE THREAD

**Issue by ssteinerx** [uranusjr/macdown#484]
I saw the note about CocoaPods 0.37 and even after following the instructions, I'm getting the handlebars build issue.

Just to make sure, I nuked the Pods subdir and:

```
# bundle exec pods install
```

Identical result; handlebars fails with ARC forbids Objective-C objects in struct.

Any idea how to get around this?

Thanks!

**Comment by uranusjr** [comment]
This is fixed now. Run `bundle install` again to upgrade CocoaPods, and the rest should work. I’ve also updated the instructions in README, but please feel free to report if there’re any problems.
