### ISSUE TITLE
Crash after viewing versions

### ISSUE THREAD

**Issue by ssteinerx** [uranusjr/macdown#485]
The file has changed on disk (I edited with another open editor), but MacDown was not showing the changes (need to hook fsevents?).

So, I thought I might be able to force it to reread by viewing versions.  Viewed versions, selected the same one I'd been editing, then got this crash on return to MacDown.

https://gist.github.com/ssteinerx/6ece3a329e271e2378d0

**Comment by willwhitney** [comment]
Confirmed that viewing versions and then hitting "Done" results in a crash.
