### ISSUE TITLE
Simplest reference link doesn't work

### ISSUE THREAD

**Issue by ssteinerx** [uranusjr/macdown#487]
This text:
```
[x Composer][composer]

[composer]: https://getcomposer.org/ 	"Composer"
```

Should produce this (all I'm doing is letting GitHub's markdown engine render this to prove that what I expect is correct):

[x Composer][composer]

[composer]: https://getcomposer.org/ 	"Composer"

Instead shows this in MacDown:

![screen shot 2015-11-02 at 10 52 46 am](https://cloud.githubusercontent.com/assets/43063/10886409/f17a4276-814f-11e5-848d-5b1d2920b4c1.png)

**Comment by uranusjr** [comment]
MacDown uses a slightly different syntax:

~~~
[x Composer]

[x Composer]: https://getcomposer.org/
~~~

**Comment by ssteinerx** [comment]
What the heck is the point of a Markdown editor that only renders properly in its own preview window?

**Comment by uranusjr** [comment]
I assume you do not realise both syntaxes work on GitHub.

**Comment by ssteinerx** [comment]
That's irrelevant; they're both valid syntaxes and I don't write all the Markdown I edit so the alternative form, which also works, should be supported.

S
