### ISSUE TITLE
Feature request: hide titlebar

### ISSUE THREAD

**Issue by bartv42** [uranusjr/macdown#493]
It would be great if MacDown could hide its titlebar when not in fullscreen mode, similar to IA Writer or Typed.

**Comment by Jmuccigr** [comment]
Serious question: isn't that what fullscreen is for?

**Comment by bartv42** [comment]
Well yes and no. I've seen colleagues use this 'titlebar-less' mode while not in full-screen and I really like that clutter-less kind of view. Often I don't need a full-screen (especially not when I'm on my 27" iMac - it's just too big). It's not a big thing, I know, just a little more 'zen' ;-)

**Comment by bartv42** [comment]
I suppose this is a duplicate of #79

**Comment by JayHoltslander** [comment]
@bartv42 
Then what would you "grab" to move the window around? 
Where would the minimize a close buttons live?

**Comment by bartv42** [comment]
@JayHoltslander #79 describes that perfectly - only hide the titlebar when the mouse is inactive. Once you start typing, hide it. Move the mouse again and it re-appears. Maybe even better: show it only when the mouse is moving *inside the macdown window* - so if you move it outside the window it stays hidden.

**Comment by uranusjr** [comment]
Closing as duplicate.
