### ISSUE TITLE
Feature request: add an option to add .md filename extension

### ISSUE THREAD

**Issue by bartv42** [uranusjr/macdown#497]
It would be great if my files can automatically get the *.md file extension, making them that much easier to open.

**Comment by Jmuccigr** [comment]
Mine do. That is, upon saving, MacDown suggests a name that has the extension already on it.

**Comment by bartv42** [comment]
How odd! Mine certainly doesn't. I'm on version 0.5 (670), maybe that's it?

![screen shot 2015-11-12 at 17 13 07](https://cloud.githubusercontent.com/assets/6816469/11123562/a8b14a94-8960-11e5-9e88-b55c0da44bab.png)

**Comment by uranusjr** [comment]
The extension suggestion was added way earlier than that, IIRC. Do you have this checked in Finder’s Preferences?
![screen shot 2015-11-13 at 17 21 15](https://cloud.githubusercontent.com/assets/605277/11142828/1971e1ba-8a2b-11e5-8f99-5b235acc9c7b.png)

**Comment by bartv42** [comment]
I have that setting disabled. But you're right: when I enable it, the documents will automatically get the .md extension.

This doesn't make sense to me though: the documents should always have that extension, regardless of whether I actually show them in the finder, correct?
