### ISSUE TITLE
Table renders not correct.

### ISSUE THREAD

**Issue by cyvoit** [uranusjr/macdown#502]
Table renders not correct on OSX 10.11.1 and MacDown Version 0.5.3 (697).

<img width="1244" alt="screen shot 2015-11-18 at 09 43 58" src="https://cloud.githubusercontent.com/assets/8186665/11230400/8a910a2c-8dd9-11e5-8d6a-0544f520769e.png">

**Comment by greycubesgav** [comment]
This works ok for me.

<img width="1680" alt="screen shot 2015-11-18 at 11 18 52" src="https://cloud.githubusercontent.com/assets/3426859/11237111/769314f4-8de6-11e5-8bdd-94a7e51467cb.png">

**Comment by cyvoit** [comment]
Thanks @greycubesgav! It works after i checked tables of "Block formatting".
