### ISSUE TITLE
Open from terminal with specific file

### ISSUE THREAD

**Issue by toymachiner62** [uranusjr/macdown#506]
I'm wondering if it's possible to open macdown from the command line for a specific file.

I love opening sublime from the terminal with the current directory i'm in showing in the tree structure in sublime. Is there a way I can open a specific file in macdown from the terminal?

**Comment by Jmuccigr** [comment]
```open -a MacDown "path/to/filename"```

This is a standard OS X thing. Just change the app name to use a different app.

**Comment by uranusjr** [comment]
For the record, there is a CLI utility for this.

~~~bash
$ /Applications/MacDown.app/Contents/SharedSupport/bin/macdown "path_to_file"
~~~

The above command does the exact same thing as `open`. The utility also offers extra functionalities such as opening multiple files with a single command, and creating a new file when the filename given does not exist.

Best usage of this is to add the following to your `~/.bash_profile` (or any other profile scripts you prefer):

~~~bash
macdown() {
    "$(mind kMDItemCFBundleIdentifier=com.uranusjr.macdown | head -n1)"/Contents/SharedSupport/bin/macdown" $@
}
~~~

**Comment by claytondukes** [comment]
@uranusjr, you have a typo (extra `"`)
It should be:
```
macdown() {
    "$(mdfind kMDItemCFBundleIdentifier=com.uranusjr.macdown | head -n1)/Contents/SharedSupport/bin/macdown" $@
}
```

**Comment by niklasberglund** [comment]
In the latest release version there's functionality for installing the command line tool to `/usr/local/bin/` so you can just use `macdown` without specifying path.

![image](https://cloud.githubusercontent.com/assets/331986/24133536/41a35ac6-0e30-11e7-903a-3dfda41bff23.png)

**Comment by ekilah** [comment]
FYI it seems like the utility above is broken, see https://github.com/MacDownApp/macdown/issues/990

**Comment by davedub** [comment]
> FYI it seems like the utility above is broken, see #990

still broken two years later ...?
