### ISSUE TITLE
checklist syntax don't work 

### ISSUE THREAD

**Issue by dev-xdyang** [uranusjr/macdown#513]
<img width="1226" alt="2015-12-01 12 41 38" src="https://cloud.githubusercontent.com/assets/7471748/11492482/1c92bdcc-9829-11e5-8f61-fce26b672823.png">

**Comment by uranusjr** [comment]
Can’t see the image, but the checklist syntax is an opt-in that needs to be turned on in Preferences. I works for me.

**Comment by stherold** [comment]
Works 👍
