### ISSUE TITLE
Add Byword Dark and Light theme

### ISSUE THREAD

**Issue by Leandros** [uranusjr/macdown#519]
These are two very lovely themes, I would love to have them in MacDown.

Light theme css: http://pastebin.com/tQwPPMhn
Dark theme css: http://pastebin.com/H5cVUArD

**Comment by uranusjr** [comment]
Where do the themes come from? If they are extracted from Byword I’d image there would be licensing issues.

**Comment by Leandros** [comment]
They're not extracted from Byword, they're from the final HTML.

**Comment by uranusjr** [comment]
Same thing though, if the CSS files are generated by Byword, their content is owned by Byword (unless specified otherwise). I’m closing this unless someone can get a consent from the Byword team.
