### ISSUE TITLE
"Unordered List" shortcut does not convert multiple line correctly

### ISSUE THREAD

**Issue by jackywu** [uranusjr/macdown#522]
this is the original document

![screen shot 2015-12-25 at 9 21 24 am](https://cloud.githubusercontent.com/assets/587955/11998781/0de99ec6-aae9-11e5-85be-ebd38b651a68.png)

I select multiple line and strike shortcut：shift+cmd+U，MacDown convert text like following

![screen shot 2015-12-25 at 9 21 39 am](https://cloud.githubusercontent.com/assets/587955/11998793/88c31500-aae9-11e5-80cb-29dd0bf30687.png)

![screen shot 2015-12-25 at 9 21 49 am](https://cloud.githubusercontent.com/assets/587955/11998794/8c2ff15e-aae9-11e5-8378-3b9590316e1b.png)

**Comment by Jmuccigr** [comment]
Same as #492 and #475, I think. Fixed with commit [565e638](https://github.com/uranusjr/macdown/commit/565e6384c712cc7cc6961754732d5de659a04ab7).

BTW @uranusjr, is there a new version coming out soon? This fix, at least for me, would make it worthwhile.

**Comment by jackywu** [comment]
thanks. I have checked out the master branch and build the latest binary by myself. It works.
