### ISSUE TITLE
link to section in the same document does not work

### ISSUE THREAD

**Issue by mxmaslin** [uranusjr/macdown#524]
ok i have section in document. The section is named: ### Вызов функций в API
i'm making link to the section: `[Вызов функций в API (JSON)](#вызов-функций-в-api)`
the link does not work in macdown (but works in stackedit.io)
please help with this macdown issue

**Comment by uranusjr** [comment]
MacDown does not currently generate section IDs automatically. Use this syntax instead:

~~~markdown
<span id="whatever-you-want"></span>
### Вызов функций в API

[Вызов функций в API (JSON)](#whatever-you-want)
~~~

Closing this as duplicated (will be tracked at #255).
