### ISSUE TITLE
MacDown should automatically detect when the open file is changed and reload it

### ISSUE THREAD

**Issue by nchammas** [uranusjr/macdown#529]
If I open a file in MacDown but edit and save it elsewhere, MacDown does not immediately detect the change and reload the file. MacDown does have some logic to detect changes and revert to what's on disk, but I don't fully understand it.

The behavior I'm looking for is:
* If the file open in MacDown is saved, then automatically detect changes to the file and reload it from disk without prompting.
* If the file open in MacDown has unsaved changes, then automatically detect changes to the file and prompt the user for action.

In both cases MacDown should be able to immediately detect external changes to the file as soon as they happen. I don't know how this works, but I know that Visual Studio Code, for example, does this seamlessly.

**Comment by eddiexue** [comment]
It's very useful when corperated with other IDE（like rstudio）which not convenient like macdown ：），I am strongly need this feature

**Comment by aaronscribner** [comment]
This is not resolved by the linked #564

**Comment by aaronscribner** [comment]
Opened anew 

https://github.com/MacDownApp/macdown/issues/1372
