### ISSUE TITLE
Dock Menu : Recent Files Naming

### ISSUE THREAD

**Issue by joalbright** [uranusjr/macdown#530]
Currently my recent files in dock look like this. Since all of them are Github readme files.

<img width="168" alt="screen shot 2016-01-07 at 2 47 52 pm" src="https://cloud.githubusercontent.com/assets/1536630/12180996/aa5a9094-b54d-11e5-9a65-11ba149ef40e.png">

Would it be possible to add a subtitle with the directory they are in?

**Comment by Jmuccigr** [comment]
+1

Lots of apps do just this.

**Comment by uranusjr** [comment]
Yeah. There are apps the do this for the File → Recent menu, but AFAIK there is no way to customise the Dock menu. (Please tell me if anyone stumble upon this and know how this can be done.)
