### ISSUE TITLE
Can't apply header to blank line with menu command

### ISSUE THREAD

**Issue by Jmuccigr** [uranusjr/macdown#534]
On an empty line, key any of the header format commands (cmd-1, etc). Nothing happens. I'd instead expect that the right number of ```#``` would be inserted at the front of the line.

The expected behavior occurs with unordered list and blockquote, where ```*``` and ```>``` are inserted, and even with the flanking tags, like bold.

EDIT - Interestingly when you apply the unordered list item command to a blank line, the asterisk appears, but the edit pane loses focus (or the cursor disappears). This means that if you start typing, your keystrokes go into the great beyond. Oddly (to me, anyway) hitting an arrow key restores the cursor.

In this context, issue #492 is a real bear, @uranusjr. Any idea when a new binary will be out with the fix?

**Comment by uranusjr** [comment]
I made some arbitrary decisions when I implemented the menu commands. Tweaking the title commands to work with blank lines makes sense.

The problem you mentioned in the third paragraph is interesting… Could you open a separate issue for it?

**Comment by Jmuccigr** [comment]
1. Great.
1. Done. See #534.

**Comment by uranusjr** [comment]
Just realised this and #546 are actually related, so by fixing that this also gets fixed. Programming is hard.

**Comment by Jmuccigr** [comment]
👍
