### ISSUE TITLE
Mail.app

### ISSUE THREAD

**Issue by noamtcohen** [uranusjr/macdown#536]
Hi,

Do you think it would be possible to merge macdown with Mail.app source code bundled with xcode so that the message editing window would be the macdown window?

Thanks for this great program,
Noam.

**Comment by JanX2** [comment]
I can’t find any Mail.app source code bundled with Xcode, @noamtcohen. Any pointers?

**Comment by noamtcohen** [comment]
I can't find it either... It used to be there. I've built it in Xcode a while ago since I wanted to tweek the UI.
I think it was one of the demo projects. I'm going to try downloading an older version of Xcode

**Comment by stevemoser** [comment]
@noamtcohen I wonder if the code you were looking at was for a Mail.app plugin.

**Comment by noamtcohen** [comment]
@stevemoser it wasn't, it was the actual mail.app source code. I remember compiling a version after I changed the hardcoded margins.

**Comment by uranusjr** [comment]
Closing this for lack of information. Feel free to re-open when you get more information on this.
