### ISSUE TITLE
macdown deletes files

### ISSUE THREAD

**Issue by kgignatyev** [uranusjr/macdown#539]
I have installed macdown via homebrew and opened file from shared Dropbox folder, which another person was constantly updating. Then I got complaints that I was deleting files, however they were just opened in macdown.

**Comment by uranusjr** [comment]
Deleting, or overwriting? If it’s the latter case it is fixed in #564 (not yet released).

**Comment by kgignatyev** [comment]
I was told 'deleting'

**Comment by uranusjr** [comment]
Hmm. MacDown does not manipulate the file system directly, only the file it opens (no such operation in the source code), so this does not really seem like a problem in MacDown. I’m closing this for now based on the evidence I have, but if anyone can reproduce this please open (or re-open) an issue.
