### ISSUE TITLE
Dollar signs green out editor text

### ISSUE THREAD

**Issue by shortformblog** [uranusjr/macdown#541]
Hey there,

Just wanted to point out an issue I've seen in recent versions of MacDown with dollar signs inside of markdown copy. Generally, what happens is that I'll reference two different financial numbers inside a block of text, and it'll treat the block of text as if it's a comment, ignoring any Markdown code located between the two dollar signs. It renders correctly, however, in the preview. 

Screenshot of issue in action: https://www.dropbox.com/s/stmbdrv8aaisod6/Screenshot%202016-01-26%2016.57.46.png?dl=0

**Comment by Jmuccigr** [comment]
Same as #489.
