### ISSUE TITLE
Could you add a word statistics function?

### ISSUE THREAD

**Issue by starlightme** [uranusjr/macdown#545]
THX!

**Comment by uranusjr** [comment]
Can you elaborate? I don’t understand what you mean exactly.

**Comment by starlightme** [comment]
I mean that you can add a function which help you know how many words you have typed.

**Comment by uranusjr** [comment]
We already have a word counter. You can turn it on in the Preferences.

**Comment by starlightme** [comment]
Thanks a lot. I apologize for bothering you. Your work is indeed brilliant!
