### ISSUE TITLE
Document loses focus upon applying unordered list item menu command

### ISSUE THREAD

**Issue by Jmuccigr** [uranusjr/macdown#546]
On a blank line, apply the unordered list item menu command (shift-cmd-u) by typing or selecting it from the menu. The ```*``` will be inserted, but the window will lose focus, so typed letters go into the ether. Hitting any of the arrow keys will return it (left and down put it at the end of the line, which is where it should have been, right puts it at the start of the line (oddly), up puts it on the previous line as if coming from the end of the line you were on).

Correct behavior is for the focus not to be lost and the cursor of course to be at the end of the line.

The similar block quote command doesn't show this behavior. (Interestingly hitting return when in an empty block quote starts a new block quote line, whereas hitting return in an empty list-item line ends the list.)

**Comment by uranusjr** [comment]
Fixed. Thanks for reporting!

**Comment by Jmuccigr** [comment]
👍
