### ISSUE TITLE
Swap editor and preview planes?

### ISSUE THREAD

**Issue by zkiraly** [uranusjr/macdown#551]
Can we have a setting in Preferences to allow having the Preview on the left and Editing on the right? Thank you.

**Comment by jkulesza** [comment]
Do you not see the second from the bottom?

<img width="366" alt="screen shot 2016-02-03 at 4 54 14 pm" src="https://cloud.githubusercontent.com/assets/9939059/12798324/c7ccc63e-ca96-11e5-8807-45879f9d6b9b.png">

**Comment by zkiraly** [comment]
Oh my god! I swear I did not see it! Even though I looked! Thank you for pointing that out.

**Comment by jkulesza** [comment]
No worries, this sort of thing happens to me all the time.  However, it's nice when something you want is already there for the taking.

**Comment by uranusjr** [comment]
We’re standing on the shoulders of… other users who had the same need.

Anyway, closing this.
