### ISSUE TITLE
Cache unsaved files on quit without asking to save (as in Sublime Text)

### ISSUE THREAD

**Issue by ivosabev** [uranusjr/macdown#554]
I would love to not be forced to save my files unsaved files when I quit the application and have them show up as I start macDown again. I know it already has the functionality as if I "force quit" the application it would bring back my unsaved files. But if I try to quit it regularly it would force me to review and save the files.

**Comment by uranusjr** [comment]
MacDown uses OS X’s built-in preference for this. If you want it to keep unsaved documents, uncheck **Close windows when quitting an app** in **System Preferences → General**.

**Comment by ivosabev** [comment]
I am not keen on relaying on a system-wide preference. For now I am just using force quit, which gives the Sublime Text behavior.

**Comment by dlgoodchild** [comment]
Where are these unsaved files stored?
I had many, and I've just reopened MacDown to find they haven't been restored. I'm hoping to recover some information.

**Comment by uranusjr** [comment]
They are managed by the operating system, opaque to app developers. Some kind of Apple magic 🤷🏻‍♂️

**Comment by ghost** [comment]
ok very long tima ago this, but for anyone who is looking for this, i just had this problem.
in terminal:
open $TMPDIR

then search for file extention .md in folder (so not 'this mac' but shown as 'T')
I just found back my file!
