### ISSUE TITLE
Make keyboard shortcut for "Don't Save" in Save File dialog

### ISSUE THREAD

**Issue by klokie** [uranusjr/macdown#556]
When closing a window without saving the file, there should be a keyboard shortcut to do that. 
CMD-D seems to be the standard.

**Comment by Jmuccigr** [comment]
What apps have it?

**Comment by klokie** [comment]
* [Atom](https://atom.io/)
* [TextMate](http://macromates.com/)
* [Sublime Text](https://www.sublimetext.com/)
* [Microsoft Word](https://products.office.com/en-us/word)
to name a few…

**Comment by Jmuccigr** [comment]
Ah, you mean that when you close the doc, you can hit cmd-D for "don't save" the file or changes? That's what TextMate does for me.

If that's it, I've actually filed a bug with Apple about this. The combined "Do you want to save?" and "where do you want to save?" dialog that MacDown uses (among other apps) grabs the cmd-D for the location part of that and moves you to the Desktop. I understand the convenience of combining the two dialogs, but years of muscle memory hitting cmd-D makes me hate it. I'm not sure there is a command equivalent for "don't save" with that dialog.

Additionally I think it was standard early on to allow cmd-<letter> to work for the first button whose text began with <letter>. Not everyone followed it (MS comes to mind), but it was handy. I think it's fairly uncommon now, though it sometimes works.

**Comment by klokie** [comment]
Thanks for the great response. I hadn't realized that was an OS thing.
Now that I know that I found a way to [Return the “Don’t Save” Keyboard Shortcut to Command+D in Mac OS X](http://osxdaily.com/2011/08/15/return-the-dont-save-keyboard-shortcut-to-commandd-in-mac-os-x-lion/). Cheers

**Comment by Jmuccigr** [comment]
Ooh, nice. I didn't even know about the delete thing.

**Comment by getaaron** [comment]
We should close this issue.
