### ISSUE TITLE
Sparkle Security Vulnerability

### ISSUE THREAD

**Issue by Okeanos** [uranusjr/macdown#558]
MacDown appears to be using Sparkle 1.7.1 which according to https://vulnsec.com/2016/osx-apps-vulnerabilities/ and https://github.com/sparkle-project/Sparkle/releases/tag/1.13.1 makes it vulnerable to a Man in the Middle attack if HTTP appcast URLs are used.

`MacDown-Info.plist` uses HTTP URLs and not HTTPS. Any chance this can be fixed?

**Comment by getaaron** [comment]
Looks like this was fixed in https://github.com/uranusjr/macdown/commit/70dca931a0bf29616606228b7e48d1803a095591

**Comment by Okeanos** [comment]
Yeah, you are right. The current release on the official website does use 1.13.1 but it has to be manually downloaded from there.

With the advent of [Let's Encrypt](https://letsencrypt.org) it would still be nice if the feed urls could be updated to SSL, though.

**Comment by uranusjr** [comment]
The reason we use HTTP is not lack of an SSL certificate, but that we’re on the free tier of Herolu, which does not support HTTPS. I’d love to hear about possible solutions.

**Comment by JanX2** [comment]
@uranusjr What about moving the hosting of the binaries and Sparkle metadata to github?

**Comment by uranusjr** [comment]
The binaries are already on GitHub. But the metadata is currently generated programatically, and can’t be hosted on GitHub. I’m willing to try if someone can offer a nice way to generate appcast though.
