### ISSUE TITLE
Add option to reformat text

### ISSUE THREAD

**Issue by jmmv** [uranusjr/macdown#560]
It would be nice to have an option (e.g. under *Edit > Transformations > Refill*) to refill paragraphs. I.e. to join short lines together and end up with one long line per paragraph.

I currently have some Markdown documents with short lines, and editing these in MacDown is annoying because MacDown assumes one long line per paragraph. The proposed option above would let me select the whole text, click the menu, and get the selected paragraphs refilled so that each had a single (very long) line.

It'd be better to have the option of specifying the maximum length of a line and having MacDown respect that for refilling purposes... but I can see how this does not fit the current interface of MacDown.

**Comment by getaaron** [comment]
I don't think this is a common enough use case to add to MacDown, but you can accomplish this already by doing a find-and-replace, and pasting a hard return into the "Find" field

**Comment by Jmuccigr** [comment]
There are also OS X services that do this. I use [WordService](http://www.devontechnologies.com/products/freeware.html).

**Comment by jmmv** [comment]
Well, I don't know if this is a common-enough use case (so I'll let you decide), but the cases that I cared about are files that use Markdown formatting but that should be readable in plain-text format easily. For example: all `README.md` files in GitHub, where long lines would cause some ugly formatting when viewing their contents in the console but which would be awesome to edit within MacDown alone.

Remember that Markdown documents are intended to be as readable in plain-text format as in their rendered form. Long lines hinder the former.
