### ISSUE TITLE
Pre-Process Error preparing HTML-CSS output

### ISSUE THREAD

**Issue by chrislessard** [uranusjr/macdown#561]
Without changing anything, I seem to have lost the ability to use in editor math rendering. Playing around has shown that I can no longer use some HTML tags, like the <img> tag, successfully either. Any ideas?

**Comment by chrislessard** [comment]
![screen shot 2016-02-09 at 11 44 26 pm](https://cloud.githubusercontent.com/assets/8469231/12938873/2ea0c8f2-cf87-11e5-84e1-fc64016e21a4.png)

**Comment by emeth-kim** [comment]
Is it solved?
