### ISSUE TITLE
MacDown processes footnotes inside fenced code

### ISSUE THREAD

**Issue by Jmuccigr** [uranusjr/macdown#570]
MacDown interprets markdown footnotes within fenced code. This for example (where I've spaced out the back ticks so they appear):

```
` ` `
hi[^1]

[^1]: the text
` ` `
```

is displayed in the Preview pane as

```
hi[^1]
```

IOW, the footnote itself disappears.

That's a bug, no? Maybe Hoedown? I see bug [# 130](https://github.com/hoedown/hoedown/issues/103) over there, which looks similar, but was allegedly fixed.

**Comment by uranusjr** [comment]
Hoedown fixes this by a complete rewrite, but the new code base is not production-ready, so MacDown still uses the old one, which does contain the bug.

**Comment by Jmuccigr** [comment]
Got it. I'll close this then.
