### ISSUE TITLE
There's no code highlight !!! Where is code highlight function?

### ISSUE THREAD

**Issue by cocoyimasa** [uranusjr/macdown#572]
I'm Crying!!!
Why don't  python and js code highlight show?
<img width="1136" alt="2016-02-27 1 11 27" src="https://cloud.githubusercontent.com/assets/7418740/13370934/ab3410a2-dd53-11e5-8e48-5c5684b415db.png">

**Comment by uranusjr** [comment]
![untitled](https://cloud.githubusercontent.com/assets/605277/13370959/51c89096-dd54-11e5-8d8d-3a3ef342076f.png)
