### ISSUE TITLE
Feature request: opening of folders

### ISSUE THREAD

**Issue by oeed** [uranusjr/macdown#578]
One thing I always wished Mou could do was open folders Sublime Text style.

Essentially, dragging a folder onto the icon or through the File menu would have a sidebar tree of the directory, allowing you to easily open and create files in the folder.

<img width="777" alt="screen shot 2016-03-03 at 9 04 05 pm" src="https://cloud.githubusercontent.com/assets/3835991/13488040/94ffa484-e183-11e5-80e8-7dd5b617cd7d.png">

I am wanting to use MacDown for university notes and being able to use a folder would make doing so considerably easier!

**Comment by uranusjr** [comment]
This is essentially the same request as #141. I am not in favour of a tree view in MacDown (doesn’t belong to a text editor IMO), but I’m open if anyone implements it.

This will be closed as duplicate.
